apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  serviceAccountName: hello-world-acc
  containers:
  - name: hello-world
    image: busybox
    command: ['sh', '-c', 'echo "Hello, World!" && sleep 3600']
