apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ vars.SERVICEACCOUNT }}
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${{ vars.ROLE }}
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello-world-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ${{ vars.SERVICEACCOUNT }}
  namespace: default
roleRef:
  kind: Role
  name: ${{ vars.ROLE }}
  apiGroup: rbac.authorization.k8s.io
